# # Informacion de Proyecto - Project information
# site_name: Apuntes
# site_description: Apuntes de Lenguajes de Programación.
# site_author: Julio Corbaz - JCC Producciones.
# site_dir: docs
# docs_dir: src
# #repo_name: "GITHUB"
# #repo_url: https://github.com/corbaz/apuntes
# #edit_uri: https://github.com/corbaz/apuntes/edit/main/docs/

# # Copyright
# copyright: Copyright &copy <a href="https://juliocorbaz.000webhostapp.com" target="_blank" rel="noopener">Julio Corbaz</a>

# # Text direction (can be ltr or rtl), default: ltr
# #direction: rtl

# nav:
#   - Home: index.md
#   - Lenguajes:
#     - Svelte: svelte/svelte.md
#     - Tailwind: tailwind/tailwind.md
#   #  - Xamarin:  xamarin/xamarin.md
#     - MkDocs: mkdocs/mkdocs.md

# # Configuration Theme
# theme:
#   name: material
#   custom_dir: src/material
#   #hljs_style: 'An Old Hope'
#   shortcuts:
#     help: 191    # ?
#     next: 78     # n
#     previous: 80 # p
#     search: 83   # s

#   # 404 page
#   static_templates:
#     - 404.html

#   # Don't include MkDocs' JavaScript
#   include_search_page: false
#   search_index_only: true

#   # Default values, taken from mkdocs_theme.yml
#   language: es
#   features:
#     - navigation.tabs
#     #- navigation.instant
#   palette:
#     #scheme: default slate preference dracula
#     #red  #pink  #purple  #deep purple  #Indigo  #blue  #light blue  #cyan  #teal  #green  #light green  #lime  #yellow  #amber  #orange  #deep orange  #brown   #grey   #blue grey  
#     scheme: default
#     primary: pink
#     accent: green
#     toggle:
#       icon: material/.icons/material/ab-testing
#       name: Switch to light mode
#     scheme: slate
#     primary: green
#     accent: blue
#     toggle:
#       icon: material/.icons/material/ab-testing
#       name: Switch to dark mode

#   font:
#     text: Roboto
#     code: Roboto Mono
#   favicon: assets/favicon.ico
#   icon:
#     logo: logo/logo

# # Customization Extra
# extra:
#   #generator: false
#   search:
#     language: "es, en"        
#   social:
#     - icon: fontawesome/brands/github
#       link: https://github.com/corbaz
#     - icon: fontawesome/brands/facebook
#       link: https://www.facebook.com/JulioCorbaz
#     - icon: fontawesome/brands/gmail
#       link: mailto://julio.corbaz@gmail.com
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/julio_corbaz
#     - icon: fontawesome/brands/linkedin
#       link: https://www.linkedin.com/in/julio-corbaz/
#     - icon: fontawesome/brands/instagram
#       link: https://www.instagram.com/julio.cesar.corbaz/

# # CSS
# extra_css:
#   - assets/css/main.css
#   - assets/libs/magnific-popup/magnific-popup.css

# # JavaScript 
# extra_javascript:
#   - assets/libs/js/extra.js

# # Extensions
# markdown_extensions:
#   - admonition
#   - abbr
#   - attr_list
#   - def_list
#   - codehilite
#   - footnotes
#   - meta
#   - smarty
#   - toc:
#       permalink: false
#   - sane_lists
#   - pymdownx.arithmatex:
#       generic: true
#   - pymdownx.details
#   - pymdownx.inlinehilite
#   - pymdownx.mark
#   - pymdownx.progressbar
#   - pymdownx.snippets
#   - pymdownx.tabbed
#   - pymdownx.tasklist:
#       custom_checkbox: true
#   - pymdownx.tilde

# plugins:   
#   - search
#       min_search_length: 2
#   - minify:
#       minify_html: true
#       minify_js: true
#       htmlmin_opts:
#         remove_comments: true
#       #js_files:
#           #- my/javascript/dir/file1.js          

# # Google Analytics
# google_analytics:
#   - 'UA-108885860-1'
#   - 'auto'

# Informacion de Proyecto - Project information
site_name: Apuntes
site_description: Apuntes de Lenguajes de Programación.
site_author: Julio Corbaz - JCC Producciones.
site_dir: docs
docs_dir: src
#repo_name: "GITHUB"
#repo_url: https://github.com/corbaz/apuntes
#edit_uri: https://github.com/corbaz/apuntes/edit/main/docs/

# Copyright
copyright: Copyright &copy <a href="https://juliocorbaz.000webhostapp.com" target="_blank" rel="noopener">Julio Corbaz</a>

nav:
    - Home: index.md
    - Lenguajes:
          - Svelte: svelte/svelte.md
          - Prueba: svelte/prueba.md
          - Tailwind: tailwind/tailwind.md
          - MkDocs: mkdocs/mkdocs.md

# Configuration
theme:
  name: null
  custom_dir: src/material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: es
  features:
    - navigation.tabs
    #- navigation.instant
    - search.suggest
    - search.highlight
    
  palette:
    #scheme: default slate dracula
    #red  #pink  #purple  #deep purple  #Indigo  #blue  #light blue  #cyan    #teal  #green  #light green  #lime  #yellow  #amber  #orange  #deep orange
    #brown  #grey  #blue grey
    - scheme: default
      primary: red
      accent: yellow
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - scheme: slate
      primary: pink
      accent: green
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.ico
  icon:
    logo: logo/logo

extra:
  generator: false
  search:
    language: "es, en"        
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/corbaz
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/JulioCorbaz
    - icon: fontawesome/brands/gmail
      link: mailto://julio.corbaz@gmail.com
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/julio_corbaz
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/julio-corbaz/
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/julio.cesar.corbaz/

extra_css:
  - assets/css/main.css
  - assets/libs/magnific-popup/magnific-popup.css
  
extra_javascript:
  - assets/libs/js/extra.js

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: false
  - pymdownx.arithmatex
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.mark

plugins:
  - search:
      min_search_length: 3
      lang:
        - es
        - en
      separator: '[\s\-\.]+'
  #pip install mkdocs-minify-plugin 
  - minify:
      minify_html: true
      minify_js: true
      htmlmin_opts:
          remove_comments: true
      js_files:
          - assets/libs/js/extra.js